POST http://localhost:8080/messages
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "pageId" : "FIRST_PAGE",
  "text" : "Bye!"
}

###
GET http://localhost:8080/WebApplicationForMetallists_war/files/init

###

GET http://localhost:8080/WebApplicationForMetallists_war/files/convert

###

GET http://localhost:8080/WebApplicationForMetallists_war/users/2/files/png/convert

###

GET http://localhost:8080/WebApplicationForMetallists_war/users/2/files/information

###